apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name:  nackFlask
  namespace: nack2529
  labels: 
    app:  nackFlask 
spec: 
  selector: 
    matchLabels: 
      app: nackFlask 
  replicas: 1 
  strategy: 
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app:  nackFlask 
    spec: 
      containers: 
      - name:  nackFlask 
        image:  nack2529/flask_app 
        resources: 
          requests: 
            cpu: 100m 
            memory: 100Mi 
          limits: 
            cpu: 100m 
            memory: 100Mi 
        ports: 
        - containerPort:  5000 
          name:  nackFlask 
        imagePullPolicy: Always 
      restartPolicy: Always 
 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: nackFlask 
  namespace: nack2529
spec: 
  selector: 
    app: nackFlask 
  type: LoadBalancer 
  sessionAffinity: None 
  sessionAffinityConfig: 
    clientIP: 
      timeoutSeconds: 10800 
  ports: 
  - name: nackFlask 
    protocol: TCP 
    port: 80 
    targetPort: 5000 